Add Accrescent button to README
mollyim/mollyim-android pull request #187
Opened 2023-04-30 18:31 UTC by lazytownfan

* Add the "Get it on Accrescent" button to the README
* Resolves #186
    * I've tried my best to imitate the line wrapping for the F-Droid button

2023-05-01 08:25 UTC, valldrac commented
@matchboxbananasynergy is right. The banner should be moved after the paragraph that tells there are two variants, and then mention that FOSS is available in Accrescent too.

2023-05-01 19:10 UTC, valldrac requested changes
See previous discussion.

2023-05-02 00:45 UTC, lazytownfan commented
I've moved the Accrescent button after the first mention of Molly-FOSS.

2023-05-02 22:50 UTC, valldrac approved these changes

2023-05-02 22:50 UTC, merged